import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header/Header";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="max-w-[1920px] mx-auto">
            <Header></Header>

            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
